baseURL = 'https://muzhy.github.io/'
languageCode = 'zh-cn'
title = '木章永的个人博客'
theme = 'PaperMod'
defaultcontentlanguage = 'zh'
enableRobotsTXT = true

pagination.pagerSize = 20

[markup.hightlight]
style = 'tango'

[params]
  author = '木章永'
  info = '普通上班族'
  description = '木章永的个人博客'
  avatarURL = 'images/avatar.jpg'     
  faviconSVG = 'images/favicon.svg'
  keywords = ["Blog", "博客", "programer"]
  since = 2023
  math = true
  enableTwemoji = true
  colorScheme = 'auto'

[[params.social]]
  name = 'GitHub'
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/muzhy/"

[[params.social]]
  name = 'Email'
  icon = "fa fa-email-bulk fa-2x"
  weight = 2
  url = "mailto:zhangyong_chen@foxmail.com"

[[menu.main]]
  name = 'Posts'
  weight = 1
  url = 'posts/'
[[menu.main]]
  name = 'About'
  weight = 2
  url = 'about/'

[[menu.main]]
  name = 'categories'
  url = 'categories/'
  weight = 3

[taxonomies]
  category = 'categories'
  tag = 'tags'
