baseURL = 'https://muzhy.github.io/'
languageCode = 'zh-cn'
title = '木章永的个人博客'
theme = 'hugo-coder'
defaultcontentlanguage = 'zh'

paginate = 20

disqusShortname = 'muzhy'

[markup.hightlight]
style = 'tango'

[params]
  author = '木章永'
  info = '普通上班族'
  description = '木章永的个人博客'
  keywords = 'blog,developer,博客,开发者'
  avatarURL = 'images/avatar.jpg'     
  faviconSVG = 'images/favicon.svg'
  
  since = 2023
  math = true
  enableTwemoji = true
  colorScheme = 'auto'

[[params.social]]
  name = 'GitHub'
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/muzhy/"

[[menu.main]]
  name = 'Posts'
  weight = 1
  url = 'posts/'
[[menu.main]]
  name = 'About'
  weight = 2
  url = 'about/'

[taxonomies]
  category = 'categories'
  tag = 'tags'
  author = 'authors'
