baseURL = 'https://muzhy.github.io/'
languageCode = 'en'
title = "muzhy's blog"
theme = 'dream'
defaultcontentlanguage = 'en'
enableRobotsTXT = true
hasCJKLanguage = false

pagination.pagerSize = 20

[markup.hightlight]
style = 'tango'

[params]
  author = "muzhy"
  description = "muzhy's blog"
  avatar = 'images/avatar.jpg'
  keywords = ["Blog"]
  favicon = 'images/favicon.svg'
  math = true
  enableTwemoji = true
  colorScheme = 'auto'
  lightTheme = "emerald"
  darkTheme = "forest"
  motto = "Software is a world of imagination."
  email = "muzhy_c@foxmail.com"
  headerTitile = "muzhy's blog"
  # footerBottomText = "微信公众号：午夜游鱼"
  siteStartYear = 2023
  noDefaultSummaryCover = true

[[params.social]]
  name = 'GitHub'
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/muzhy/"

[[params.social]]
  name = 'Email'
  icon = "fa fa-email-bulk fa-2x"
  weight = 2
  url = "mailto:muzhy_c@foxmail.com"

[[menu.main]]
  name = 'Posts'
  weight = 1
  url = 'posts/'
[[menu.main]]
  name = 'About'
  weight = 2
  url = 'about/'

[[menu.main]]
  name = 'categories'
  url = 'categories/'
  weight = 3

[taxonomies]
  category = 'categories'
  tag = 'tags'
